<option value="usd">US Dollar ($)</option>
<option value="idr">Indonesian Rupiah (Rp)</option>
<option value="twd">New Taiwan Dollar (NT$)</option>
<option value="eur">Euro (€)</option>
<option value="krw">South Korean Won (₩)</option>
<option value="jpy">Japanese Yen (¥)</option>
<option value="rub">Russian Ruble (₽)</option>
<option value="cny">Chinese Yuan (¥)</option>
<option value="aed">United Arab Emirates Dirham (د.إ)</option>
<option value="ars">Argentine Peso ($)</option>
<option value="aud">Australian Dollar ($)</option>
<option value="bdt">Bangladeshi Taka (৳)</option>
<option value="bhd">Bahraini Dinar (.د.ب)</option>
<option value="bmd">Bermudian Dollar ($)</option>
<option value="brl">Brazil Real (R$)</option>
<option value="cad">Canadian Dollar ($)</option>
<option value="chf">Swiss Franc (Fr.)</option>
<option value="clp">Chilean Peso ($)</option>
<option value="czk">Czech Koruna (Kč)</option>
<option value="dkk">Danish Krone (Kr.)</option>
<option value="gbp">British Pound Sterling (£)</option>
<option value="hkd">Hong Kong Dollar ($)</option>
<option value="huf">Hungarian Forint (Ft)</option>
<option value="ils">Israeli New Shekel (₪)</option>
<option value="inr">Indian Rupee (₹)</option>
<option value="kwd">Kuwaiti Dinar (د.ك)</option>
<option value="lkr">Sri Lankan Rupee (රු)</option>
<option value="mmk">Burmese Kyat (K)</option>
<option value="mxn">Mexican Peso ($)</option>
<option value="myr">Malaysian Ringgit (RM)</option>
<option value="ngn">Nigerian Naira (₦)</option>
<option value="nok">Norwegian Krone (kr)</option>
<option value="nzd">New Zealand Dollar ($)</option>
<option value="php">Philippine Peso (₱)</option>
<option value="pkr">Pakistani Rupee (₨)</option>
<option value="pln">Polish Zloty (zł)</option>
<option value="sar">Saudi Riyal (ر.س)</option>
<option value="sek">Swedish Krona (kr)</option>
<option value="sgd">Singapore Dollar ($)</option>
<option value="thb">Thai Baht (฿)</option>
<option value="try">Turkish Lira (₺)</option>
<option value="uah">Ukrainian hryvnia (₴)</option>
<option value="vef">Venezuelan bolívar fuerte (Bs)</option>
<option value="vnd">Vietnamese đồng (₫)</option>
<option value="zar">South African Rand (R)</option>
<option value="xdr">IMF Special Drawing Rights (XDR)</option>